:guid: %guid%
:user: %user%
:markup-in-source: verbatim,attributes,quotes

== Orientation about the environment

In this workshop you will work with the following tools:
* OpenShift Container Platform
* Openshift DevSpaces as the Cloud based Development Environment
* OpenShift Pipelines based on Tekton
* OpenShift Serverless based on Knative
* OpenShift Monitoring based on Prometheus
* Grafana Operator
* OpenShift Logging based on Elasticsearch, Kibana, and Fluentd ******TODO: confirm EFK or Loki
* Quarkus, Micronaut, and Spring Boot
* Hyperfoil for load testing execution

The following diagram describes the architecture of the environment you will work with:

******TODO: Add a simple diagram describing the environment******


:guid: %guid%
:user: %user%
:ssh_command: %ssh_password%
:markup-in-source: verbatim,attributes,quotes
:my_deep_var_underbars: %my_deep_var%
:my_deep_var_dots: %my.deep.var%

== Overview

You can access ENV variables as flattened % surrounded variables in these templated asciddoc files.

=== variables from ENV as asciidoc attributes

NOTE: json objects are flattned and joined with a `.`.
As a side-effect of the `.`, any character will match the `.` in the variable name.

.Example: All of these function
----
:my_deep_var_underbars: %my_deep_var%
:my_deep_var_dots: %my.deep.var%

my_deep_var_underbars: {my_deep_var_underbars}
my_deep_var_dots: {my_deep_var_dots}

my_deep_var_underbars: %my_deep_var%
my_deep_var_dots: %my.deep.var%
----

== Intro

In this workshop you will... to be completed by the workshop developer.
The following content is an example of what to include in an overview.

=== Lab Access

You can access your lab environment as {user} with password "{ssh_password}" with the following command:

[source,bash,options="nowrap",subs="{markup-in-source}"]
----
%ssh_command%
----

Your lab GUID is "{guid}".

An example var was set to %example_var%.

=== Workshop Information

Informational messages generated for your workshop:

[source,bash,options="nowrap"]
----
%user_info_messages%
----
